version: '3.8'

services:
  backend:
    build: ./backend
    container_name: lms-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: lms-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/app

  nginx:
    image: nginx:latest
    container_name: lms-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend

  db:
    image: nouchka/sqlite3:latest
    container_name: lms-db
    volumes:
      - ./backend/database:/data
    restart: always
